### ISSUE TITLE
Build "Unified Edict Stream".

### ISSUE THREAD

**Issue by r002** [r002/rittr#20]
# Implement this feature for the new `Space GUI`.

### GUI User Story:

When the user clicks on `Unified Edict Stream`, the GUI loads and shows all edict cards promulgated by the user's leaders.

---

### Tasks:
- [x] Load all of the mock data into the db.
- [x] Render the Edict Grid from the mock db data.

---

Shows unified stream of all edicts promulgated by a user's alphas.

- [ ] Server-side service
- [ ] REST API
- [ ] Tests
- [ ] GUI

**Comment by r002** [comment]
**Today's progress:**

- [Started documenting my API.](https://github.com/r002/rittr/wiki/API)
- Implemented "Unified EdictStream" feature:

![image](https://user-images.githubusercontent.com/45280066/89005584-d531d780-d2d2-11ea-80c5-0b0532fb457d.png)

**Comment by r002** [comment]
**_Today's progress:_**

We're live!  Here's the temp link that bypasses all auth:
https://rittr.herokuapp.com/?id=1&otp=mock_otp_for_tests_good_until_2021
https://rittr.herokuapp.com/v1/user/1/edictstream?otp=mock_otp_for_tests_good_until_2021

![image](https://user-images.githubusercontent.com/45280066/89152829-c8f78580-d531-11ea-9eeb-1dd88f2e563e.png)

![image](https://user-images.githubusercontent.com/45280066/89153015-196ee300-d532-11ea-8a6b-0258b9c1b517.png)

**Comment by r002** [comment]
### Finished:
https://rittr.herokuapp.com/home/?id=1&otp=mock_otp_for_tests_good_until_2021

![image](https://user-images.githubusercontent.com/45280066/93012395-0d813280-f56e-11ea-8262-4f5efc3847b3.png)
